"""Fase 2 - Migration inicial com 12 tabelas

Revision ID: bf6d7e0ba78f
Revises: 
Create Date: 2026-03-26 20:44:35.355800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf6d7e0ba78f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimensoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('ferramentas_ia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('custo', sa.String(length=30), nullable=False),
    sa.Column('complexidade', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('setores_alvo', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilizadores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('utilizadores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utilizadores_email'), ['email'], unique=True)

    op.create_table('empresas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('setor', sa.String(length=100), nullable=False),
    sa.Column('num_colaboradores', sa.Integer(), nullable=True),
    sa.Column('localizacao', sa.String(length=200), nullable=True),
    sa.Column('ano_fundacao', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['utilizador_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_utilizador_id'), ['utilizador_id'], unique=False)

    op.create_table('indicadores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dimensao_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dimensao_id'], ['dimensoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    with op.batch_alter_table('indicadores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indicadores_dimensao_id'), ['dimensao_id'], unique=False)

    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('nivel_global', sa.Integer(), nullable=True),
    sa.Column('pontuacao_global', sa.Float(), nullable=True),
    sa.Column('iniciado_em', sa.DateTime(), nullable=False),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avaliacoes_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_avaliacoes_estado'), ['estado'], unique=False)

    op.create_table('perguntas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicador_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('tipo_resposta', sa.String(length=30), nullable=False),
    sa.Column('opcoes_json', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('obrigatoria', sa.Boolean(), nullable=False),
    sa.Column('ajuda_contextual', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['indicador_id'], ['indicadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('perguntas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_perguntas_indicador_id'), ['indicador_id'], unique=False)

    op.create_table('conversas_ia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversas_ia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversas_ia_avaliacao_id'), ['avaliacao_id'], unique=False)

    op.create_table('relatorios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('conteudo_json', sa.Text(), nullable=True),
    sa.Column('pontos_fortes', sa.Text(), nullable=True),
    sa.Column('necessidades', sa.Text(), nullable=True),
    sa.Column('recomendacoes_texto', sa.Text(), nullable=True),
    sa.Column('caminho_pdf', sa.String(length=500), nullable=True),
    sa.Column('gerado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avaliacao_id')
    )
    op.create_table('respostas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.Column('valor_texto', sa.Text(), nullable=True),
    sa.Column('valor_numerico', sa.Float(), nullable=True),
    sa.Column('valor_fuzzy', sa.Float(), nullable=True),
    sa.Column('respondido_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacoes.id'], ),
    sa.ForeignKeyConstraint(['pergunta_id'], ['perguntas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avaliacao_id', 'pergunta_id', name='uq_resposta_avaliacao_pergunta')
    )
    op.create_table('resultados_dimensao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('dimensao_id', sa.Integer(), nullable=False),
    sa.Column('pontuacao', sa.Float(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('gap_critico', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacoes.id'], ),
    sa.ForeignKeyConstraint(['dimensao_id'], ['dimensoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avaliacao_id', 'dimensao_id', name='uq_resultado_avaliacao_dimensao')
    )
    op.create_table('recomendacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('relatorio_id', sa.Integer(), nullable=False),
    sa.Column('ferramenta_id', sa.Integer(), nullable=True),
    sa.Column('dimensao_id', sa.Integer(), nullable=True),
    sa.Column('justificacao', sa.Text(), nullable=False),
    sa.Column('prioridade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dimensao_id'], ['dimensoes.id'], ),
    sa.ForeignKeyConstraint(['ferramenta_id'], ['ferramentas_ia.id'], ),
    sa.ForeignKeyConstraint(['relatorio_id'], ['relatorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recomendacoes')
    op.drop_table('resultados_dimensao')
    op.drop_table('respostas')
    op.drop_table('relatorios')
    with op.batch_alter_table('conversas_ia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversas_ia_avaliacao_id'))

    op.drop_table('conversas_ia')
    with op.batch_alter_table('perguntas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_perguntas_indicador_id'))

    op.drop_table('perguntas')
    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avaliacoes_estado'))
        batch_op.drop_index(batch_op.f('ix_avaliacoes_empresa_id'))

    op.drop_table('avaliacoes')
    with op.batch_alter_table('indicadores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indicadores_dimensao_id'))

    op.drop_table('indicadores')
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_utilizador_id'))

    op.drop_table('empresas')
    with op.batch_alter_table('utilizadores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utilizadores_email'))

    op.drop_table('utilizadores')
    op.drop_table('ferramentas_ia')
    op.drop_table('dimensoes')
    # ### end Alembic commands ###
